# Generated by Django 2.1.5 on 2019-07-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageapp', '0003_auto_20190715_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_send',
            name='camera',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='message_send',
            name='message',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
