# Generated by Django 2.1.5 on 2019-07-15 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messageapp', '0005_auto_20190715_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message_recv',
            old_name='message',
            new_name='message_recv',
        ),
        migrations.RenameField(
            model_name='message_recv',
            old_name='time',
            new_name='time_recv',
        ),
        migrations.RenameField(
            model_name='message_send',
            old_name='message',
            new_name='message_send',
        ),
        migrations.RenameField(
            model_name='message_send',
            old_name='time',
            new_name='time_send',
        ),
    ]
