# Generated by Django 2.1.5 on 2019-07-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageapp', '0008_auto_20190718_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_recv',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
