# Generated by Django 2.1.5 on 2019-07-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageapp', '0009_message_recv_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_send',
            name='cmd',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
