# Generated by Django 2.2.3 on 2019-08-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageapp', '0010_auto_20190721_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_send',
            name='message_send',
            field=models.TextField(max_length=150, null=True),
        ),
    ]
